### PR TITLE
Updated Upcoming events section and also fixed a typo in past events

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**

### CODE REVIEW

**Comment by choudhary-vaibhav** [comment]
There is some merge conflict...can you fetch upstream and send the PR again.

**Comment by AK-shat-JAIN** [comment]
how to do that could you please tell

**Comment by choudhary-vaibhav** [comment]
First, go to your Github account repo
image

Then click sync fork
image

Click update branch
Then send the PR

**Comment by AK-shat-JAIN** [comment]
Now, I think it is resolved

**Comment by choudhary-vaibhav** [comment]
Great

**Comment by AK-shat-JAIN** [comment]
Thanks for Guidence

**Pull request merged**
